# -*- coding: utf-8 -*-
"""Copy of iris

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXhIpFi8JViI9O8pX4ldPzwpp9b5VIrS
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')


plt.style.use("fivethirtyeight")
# %matplotlib inline

import pandas as pd
from sklearn import datasets
import seaborn as sns

# @title Default title text
df=pd.read_csv("/content/Iris.csv")
df.head()

# to display stats about data
df.describe()

df.info()

df.shape

df.drop('Id',axis=1,inplace=True)

df.head()

df['Species'].value_counts()

#finding the null value
df.isnull().sum()

import missingno as msno
msno.bar(df)

df.drop_duplicates(inplace=True)

#checking for null values
df.isnull().sum()

#exploratory data analysis
df["SepalLengthCm"].hist()

df['SepalWidthCm'].hist()

df['PetalLengthCm'].hist()

df["PetalWidthCm"].hist()

#scatterplot
colors=['black','purple','magenta']
species=['Iris-virginica','Iris-versicolor','Iris-setosa']

for i in range(3):
  x=df[df['Species']==species[i]]
  plt.scatter(x['SepalLengthCm'],x['SepalWidthCm'],c=colors[i],label=species[i])
plt.xlabel('sepal length')
plt.ylabel('sepal width')
plt.legend()

for i in range(3):
  x=df[df['Species']==species[i]]
  plt.scatter(x['PetalLengthCm'],x['PetalWidthCm'],c=colors[i],label=species[i])
plt.xlabel('petal length')
plt.ylabel('petal width')
plt.legend()

for i in range(3):
  x=df[df['Species']==species[i]]
  plt.scatter(x['SepalLengthCm'],x['PetalLengthCm'],c=colors[i],label=species[i])
plt.xlabel('sepal length')
plt.ylabel('sepal length')
plt.legend()

for i in range(3):
  x=df[df['Species']==species[i]]
  plt.scatter(x['SepalWidthCm'],x['PetalWidthCm'],c=colors[i],label=species[i])
plt.xlabel('sepal width')
plt.ylabel('petal width')
plt.legend()

#correlation matrix
df.corr()

corr=df.corr()
fig,ax=plt.subplots(figsize=(5,4))
sns.heatmap(corr,annot=True,ax=ax)

"""***EDA***


1. Relationship between species and
 sepal length
"""

plt.figure(figsize=(15,8))
sns.boxplot(x='Species',y='SepalLengthCm',data=df.sort_values('SepalLengthCm',ascending=False))

"""2. Relationship between species and sepal width"""

df.plot(kind='scatter',x='SepalWidthCm',y='SepalLengthCm')

plt.figure(figsize=(15,10))
plt.subplot(2,2,1)
sns.violinplot(x='Species',y='PetalLengthCm',data=df)
plt.subplot(2,2,2)
sns.violinplot(x='Species',y='PetalWidthCm',data=df)
plt.subplot(2,2,3)
sns.violinplot(x='Species',y='SepalLengthCm',data=df)
plt.subplot(2,2,4)
sns.violinplot(x='Species',y='SepalWidthCm',data=df)